Donnees Acquisition Data software
===========================

:Author: Martin volpe

Dronnes is the coolest open source Acquisition Data software written entirely in Python. 

Disclaimer: This code is pretty stable but it was originally developed for a specifical task and is not ready (nor recomended) for general usage, here you can find `more information <http://volteck.net/development/2012/08/why-donnees-sucks/>`_

Features
--------

* Live data plotting
* Extensible data sources, serial port is natively supported
* Allow to record data as data logger
* Exportable charts
* E-mail reports
* Built-in web interface 
* Linux and Windows support
* Built-in SCADA sofware

Dependences
-----------

::

    linux$: sudo easy_install orbited
    linux$: sudo easy_install twisted
    linux$: sudo easy_install matplotlib
    linux$: sudo easy_install numpy
    linux$: sudo easy_install pyserial
    linux$: sudo easy_install pygtk
    linux$: sudo easy_install pygame #optional, required to use the SCADA


How to Run
----------

::

    $ cd Donnees
    $ python tilapia.py -f #this argument creates a virtual data input

Start the web server:

::    

    $ orbited --config server/orbited.cfg #start the webserver 
    
Start the SCADA:
    
::

    $ cd SCADA
    $ python SCADA.py
    

A nice real-time updated page should be available at http://localhost:8080/demo


Screenshot
----------
.. figure:: http://volteck.net/development/wp-content/uploads/2012/08/Screenshot-from-2012-08-22-234128.png
   :target: http://volteck.net/development/wp-content/uploads/2012/08/Screenshot-from-2012-08-22-234128.png


Current Version
---------------

0.2 Alpha

Author:
-------
`Martin Volpe <http://about.me/MartinVolpe>`_
